name: WebApp Test
on:
  workflow_dispatch:
  push:
    branches-ignore: ## Ignore develop and main branches to avoid an unneeded 2nd build.
      - 'develop'
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install depdendencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build --mode staging
        env:
          VITE_REACT_APP_DEPLOY_VERSION: ${{ github.sha }}
          VITE_REACT_APP_DEPLOY_ENVIRONMENT: ${{ needs.set-environment.outputs.environment }}
          VITE_REACT_APP_ANALYTICS_KEY: ${{ secrets.VITE_REACT_APP_ANALYTICS_KEY }}
          VITE_GATEWAY_IPFS_API_KEY: ${{secrets.VITE_GATEWAY_IPFS_API_KEY}}
          VITE_ETHERSCAN_API_KEY: ${{secrets.VITE_ETHERSCAN_API_KEY}}
          VITE_PINATA_CID_VERSION: ${{vars.VITE_PINATA_CID_VERSION}}
          VITE_PINATA_GATEWAY: ${{vars.VITE_PINATA_GATEWAY}}
          VITE_PINATA_JWT_API_KEY: ${{secrets.VITE_PINATA_JWT_API_KEY}}
